version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fishmachine
      MYSQL_USER: fishuser
      MYSQL_PASSWORD: fishpassword
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      #- ./migrations:/migrations # 挂载 migrations 目录

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data

volumes:
  mysql_data:
  redis_data:
